### ISSUE TITLE
Docs on IdP setup?

### ISSUE THREAD

**Issue by daum** [SURFnet/Stepup-saml-bundle#24]
Hey -

I'm working on setting up my project to act as an IdP.  I have it currently almost setup just using the simplesamlphp library, however it looks like this would provide a cleaner integration into my project.

A few questions -
- What are the metadata keys for?  
- for the SSO route where should that point/do you have an example of the controller?

If i understand this should allow me to do the following more or less:
1. Setup my symfony2 project as an IdP. I currently use FOSUserBundle.
2. When an external SP pings my service it'd all go through the Symfony2 application, if the user isn't logged in, it'll take them to the login page and then when they've logged in resume the sign on process.

Just am curious on the steps/setup for this.  If this doesn't work like I described above please let me know how it does work.

I figured if I can get this fully managed inside the Symfony app that'd be better than the final step I'm on with the non-bundled version.  I'm currently at the point I'd just need to write a custom session handler to get the session data from the database and integrated with Symfony's PDOSessionHandler.

Thanks!

**Comment by DRvanR** [comment]
Hey!

First of all thank you for your interest and apologies for the slow reaction time.

with respect to your questions:
- the metadata key is used for signing the metadata. This does not have to be the same (albeit it may) as the key used to sign the saml messages that is published in the metadata.
- an example of the SSO controller can be found [here][1] however that is a SAML gateway, not an IdP itself, sorry.

This library is intended to provide SAML communication abilities to your application, allowing fairly easy construction of the message and providing Symfony compatible Redirect (GET) and Post bindings for SAML interaction. It does not take care of everything, it integrates the SAML2 lib in an Symfony application, that's about it.

As an IdP you would have to create the actual login, consent and state saving mechanisms yourself, however that should be fairly simple, in pseudo code:

```php

public function ssoAction(Request $httpRequest)
{
    try {
        $request = $this->get('surfnet_saml.http.redirect_binding')->processRequest($httpRequest);
    } catch (Exception $e) {
        // handle error, apparently the request cannot be processed :(
    }

    if (!$userIsLoggedIn) {
        // save request so the response to this request can be created later
        // redirect to login handling
    }

    // user has apparently logged in, so we can respond immediately
    return return $this->forward('YourBundle:Saml:respond');
}

public function respondAction()
{
    // sanity check
    if (!$userIsLoggedIn) {
        // programmer error :(
    }

    $request = $yourStorageMechanism->getRequest();
    // create your SAML_Response
    $response = $this->get('your.response.factory')->createReponse($request);

    // render it
    return $this->renderSamlResponse($response);
}
```
For response creation something like [this][2] is enough.
For response rendering, check the [controller helper method][3] and the actual [view][4]

This bundle may not exactly provider all you need, but was is missing is fairly simply created. Hope this helps a bit!

Good luck!

[1]: https://github.com/SURFnet/Stepup-Gateway/blob/develop/src/Surfnet/StepupGateway/GatewayBundle/Controller/GatewayController.php#L35
[2]: https://github.com/SURFnet/Stepup-Gateway/blob/develop/src/Surfnet/StepupGateway/GatewayBundle/Service/ProxyResponseService.php#L202
[3]: https://github.com/SURFnet/Stepup-Gateway/blob/develop/src/Surfnet/StepupGateway/GatewayBundle/Controller/GatewayController.php#L252
[4]: https://github.com/SURFnet/Stepup-Gateway/blob/develop/src/Surfnet/StepupGateway/GatewayBundle/Resources/views/Gateway/consumeAssertion.html.twig

**Comment by daum** [comment]
Thanks for all the feedback, will give it a go!

**Comment by jc-fagot** [comment]
Hello, 

I'm a rookie with symfony and I have a mission : create a portal with SSO.

So, I'm trying to use stepup-saml-bundle with symfony2.8 because I tested some other and this one seems to be really simple to install. 

Well, install is ok, but I need some light with configuration, in particular with parameters, because I think your documentation is a bit poor. 
Could you explain or give an realistic example of parameter.yml with, by the way, the best place for certs files.

Thanks by advance.

**Comment by rjkip** [comment]
Hi @jc-fagot,

Great to see people using this bundle! I'm currently at work, and don't have time to go in-depth, but the following configuration should help you along:

 * [app/config/config.yml](https://github.com/SURFnet/Stepup-SelfService/blob/6edc6cba13c387d6e8d76a1988f5290924daa4ba/app/config/config.yml#L116-L132)
 * app/config/parameters.yml:

```yaml
saml_sp_publickey: '%kernel.root_dir%/../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_publickey.cer'
saml_sp_privatekey: '%kernel.root_dir%/../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_privatekey.pem'
saml_metadata_publickey: '%kernel.root_dir%/../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_publickey.cer'
saml_metadata_privatekey: '%kernel.root_dir%/../vendor/surfnet/stepup-saml-bundle/src/Resources/keys/development_privatekey.pem'
saml_remote_idp_entity_id: 'https://your-adfs-instance/metadata'
saml_remote_idp_sso_url: 'https://your-adfs-instance/single-sign-on'
saml_remote_idp_certificate: MIIEJ... # Your ADFS IdP's certificate as a string
```

As you can see, we use the development certificates that are shipped with this bundle for convenience. Obviously, don't use these in a production environment.

There is no out-of-the-box solution for authenticating a user through SAML (SSO). We implemented our own SAML firewall, which means working with the intricacies of Symfony's SecurityBundle. You say you are a rookie, so definitely read up on [how to create a custom authentication provider](http://symfony.com/doc/2.8/cookbook/security/custom_authentication_provider.html).

We developed an implementation of a SAML firewall ourselves, [here](https://github.com/SURFnet/Stepup-SelfService/blob/6edc6cba13c387d6e8d76a1988f5290924daa4ba/app/config/security.yml#L15-L23), [here](https://github.com/SURFnet/Stepup-SelfService/blob/d415fc9e81d1b0663a85f867b10ce8461345aee3/src/Surfnet/StepupSelfService/SelfServiceBundle/SurfnetStepupSelfServiceSelfServiceBundle.php#L34-L36), [here](https://github.com/SURFnet/Stepup-SelfService/blob/d415fc9e81d1b0663a85f867b10ce8461345aee3/src/Surfnet/StepupSelfService/SelfServiceBundle/Resources/config/services.yml#L108-L139) and [here](https://github.com/SURFnet/Stepup-SelfService/tree/6edc6cba13c387d6e8d76a1988f5290924daa4ba/src/Surfnet/StepupSelfService/SelfServiceBundle/Security).

If you can explain in more detail what your problems are, we can maybe give some more concrete help.

**Comment by jc-fagot** [comment]
Hi @rjkip 

Thanks for this fast answer and all of these sources. I read that now.

I'll try to create a custom authentication provider, thanks for this information.

If I have some troubles I'll post again here.

For the moment I will try to implement the missing things :)

**Comment by jc-fagot** [comment]
> We developed an implementation of a SAML firewall ourselves 

I guess if you speak about this firewall it is because it is recommanded to install it, isn't it ?

**Comment by jc-fagot** [comment]
Ok I understood about the firewall.

**Comment by jc-fagot** [comment]
UP :)

**Comment by rjkip** [comment]
What do you mean by "is it better to do mine"?

**Comment by jc-fagot** [comment]
Sorry, after read again, I made a mistake. 
The real question is : _"is it better to use your solution or do a listener myself"_ ?

**Comment by rjkip** [comment]
@jc-fagot Only you can decide whether our solution might fit your problem, or whether you need your own! :wink: I think writing your own will help you on the path of getting a better understanding of Symfony Security.

**Comment by jc-fagot** [comment]
Yep indeed :) Thanks a lot for all :)

**Comment by gabyquiles** [comment]
How can I register a remote SP so it can be able to get the Id for a user from this IdP?

**Comment by rjkip** [comment]
@gabyquiles Hi!

If I understand you correctly, you wish to configure an application as a hosted IdP. To achieve this, follow the below steps. Feel free to ask more questions, I may have forgotten to include some information!

1. Create a controller action from which you wish to serve the IdP's metadata, like [done here](https://github.com/SURFnet/Stepup-Gateway/blob/0f8e084a07661005901ba127d2f9d66324421ea5/src/Surfnet/StepupGateway/GatewayBundle/Controller/MetadataController.php#L26-L32).
1. Create a service that implements [ServiceProviderRepository](https://github.com/SURFnet/Stepup-saml-bundle/blob/330abab978c234a0e2357b679cac050525c2305c/src/Entity/ServiceProviderRepository.php) and register it as a service in your application. This repository returns information about your SP.
1. Create a controller that accepts an AuthnRequest, like [this example](https://github.com/SURFnet/Stepup-Gateway/blob/0f8e084a07661005901ba127d2f9d66324421ea5/src/Surfnet/StepupGateway/GatewayBundle/Controller/GatewayController.php#L37-L52).
1. When you're ready to send a Response, create a SAML2_Response with your desired information.
1. Send a response by rendering the Twig template included below (for a POST binding)
1. Configure the SAML bundle like the configuration below.

```twig
{# step 5 #}
<form method="post" action="{{ assertionConsumerUrlOfYourSP }}">
    {# response = base64_encode($yourResponse->toUnsignedXML()->ownerDocument->saveXML()) #}
    <input type="hidden" name="SAMLResponse" value="{{ response }}" />
    {# relayState can be passed with the AuthnRequest as a query parameter (https://github.com/SURFnet/Stepup-saml-bundle/blob/330abab978c234a0e2357b679cac050525c2305c/src/SAML2/AuthnRequest.php#L27)  #}
    {% if relayState|length > 0 %}
        <input type="hidden" name="RelayState" value="{{ relayState|escape }}" />
    {% endif %}
    <input type="submit" value="Submit"/>
</form>
```

```yaml
{# step 6 #}
# app/config/config.yml
surfnet_saml:
    hosted:
        identity_provider:
            enabled: true
            service_provider_repository: your_service_provider_repository_service # step 2
            sso_route: the_route_on_which_you_wish_to_receive_authnrequests # step 3
            public_key: /path/to/public-key.pem
            private_key: /path/to/private-key.pem
        metadata:
            entity_id_route: the_route_from_which_you_wish_to_serve_metadata # step 1
            public_key: /path/to/public-key.pem
            private_key: /path/to/private-key.pem
```
